steps:
- name: "gcr.io/cloud-builders/curl"
  args: 
      [
          'https://pets.doingdevops.com/pet', 
          '-s',
          '--max-time', '10', # related arguments are grouped on one line
      ]